language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t asishcr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true asishcr/react-test npm run test

after_success:
  - docker build -t asishcr/multi-client ./client
  - docker build -t asishcr/multi-nginx ./nginx
  - docker build -t asishcr/multi-server ./server
  - docker build -t asishcr/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push asishcr/multi-client
  - docker push asishcr/multi-nginx
  - docker push asishcr/multi-server
  - docker push asishcr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-1-002301550386"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"